app/user_management/routes.py
from .user import User
from ..extensions import db
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import login_user, logout_user, login_required
from urllib.parse import urlparse
import re

user_management = Blueprint('user_management', __name__, template_folder='templates')

@user_management.route('/register', methods=['GET', 'POST'])
def register():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        conf_password = request.form['conf_password']
        if password == conf_password:
            user = User(email=email, password=password)
            db.session.add(user)
            db.session.commit()
            flash("Udało Ci się założyć konto!\nMożesz się zalogować.", 'mess')
            return redirect(url_for('user_management.login'))
        else:
            email = request.form['email']
            flash("Hasła różnią się od siebie!", 'error')
            return render_template('register.html', last_email=email)
    return render_template('register.html')


@user_management.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form['email']
        password = request.form['password']
        user = User.query.filter_by(email=email).first()
        path = urlparse(request.referrer)
        if user and user.password == password:
            if 'follow' in path.path:
                tripID = int(re.findall(r'\d+\b', path.path)[0])
                login_user(user)
                return redirect(url_for('trips.follow', tripID=tripID))
            else:
                login_user(user)
                flash("Udało Ci się zalogować!", 'mess')
                return redirect(url_for('main.index'))

        else:
            flash("Błędne dane logowania!", 'error')
            return redirect(url_for('user_management.login'))
    return render_template('login.html')

@user_management.route('/logout')
@login_required
def logout():
    logout_user()
    flash("Wylogowałeś się!", 'mess')
    return redirect(url_for('main.index'))

app/user_management/templates/login.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple registration form</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <style>
      html, body {
      display: flex;
      justify-content: center;
      height: 100%;
      }
      body, div, h1, form, input, p {
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 16px;
      color: #666;
      }
      h1 {
      padding: 10px 0;
      font-size: 32px;
      font-weight: 300;
      text-align: center;
      }
      p {
      font-size: 12px;
      }
      hr {
      color: #a9a9a9;
      opacity: 0.3;
      }
      .main-block {
      max-width: 340px;
      min-height: 330px;
      padding: 10px 0;
      margin: auto;
      border-radius: 5px;
      border: solid 1px #fff;
      box-shadow: 1px 2px 5px rgba(0,0,0,.31);
      background: #F8FFBF;
      }
      form {
      margin: 0 30px;
      }
      .account-type, .gender {
      margin: 15px 0;
      }
      input[type=radio] {
      display: none;
      }
      label#icon {
      margin: 0;
      border-radius: 5px 0 0 5px;
      }
      label.radio {
      position: relative;
      display: inline-block;
      padding-top: 4px;
      margin-right: 20px;
      text-indent: 30px;
      overflow: visible;
      cursor: pointer;
      }
      label.radio:before {
      content: "";
      position: absolute;
      top: 2px;
      left: 0;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #EED90C;
      }
      label.radio:after {
      content: "";
      position: absolute;
      width: 9px;
      height: 4px;
      top: 8px;
      left: 4px;
      border: 3px solid #fff;
      border-top: none;
      border-right: none;
      transform: rotate(-45deg);
      opacity: 0;
      }
      input[type=radio]:checked + label:after {
      opacity: 1;
      }
      input[type=text], input[type=password] {
      width: calc(100% - 57px);
      height: 36px;
      margin: 13px 0 0 -5px;
      padding-left: 10px;
      border-radius: 0 5px 5px 0;
      border: solid 1px #cbc9c9;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09);
      background: #fff;
      }
      input[type=password] {
      margin-bottom: 15px;
      }
      #icon {
      display: inline-block;
      padding: 9.3px 15px;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09);
      background: #EED90C;
      color: #fff;
      text-align: center;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      .submit {
      width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px;
      border: none;
      background: #EED90C;
      font-size: 14px;
      font-weight: 600;
      color: #fff;
      }
      .submit:hover {
      background: #26a9e0;
      }

    </style>
  </head>
  {% include 'alerts.html' %}
  <body>
    <div class="main-block">
      <h1>Logowanie</h1>
      <form method="POST" action="{{ url_for('user_management.login') }}">
        <hr>

        <hr>


        <label id="icon" for="email"><i class="fas fa-envelope"></i></label>
        <input type="text" class="form-control" name="email" id="email" placeholder="Email" autofocus required/>
        <label id="icon" for="password"><i class="fas fa-unlock-alt"></i></label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Hasło" required/>
        <hr>

        <hr>
        <div class="btn-block">
          <button class="submit" type="submit" href="/">Zatwierdź</button>
        </div>
      </form>
    </div>
  </body>
</html>

app/user_management/templates/register.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple registration form</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <style>
      html, body {
      display: flex;
      justify-content: center;
      height: 100%;
      }
      body, div, h1, form, input, p {
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 16px;
      color: #666;
      }
      h1 {
      padding: 10px 0;
      font-size: 32px;
      font-weight: 300;
      text-align: center;
      }
      p {
      font-size: 12px;
      }
      hr {
      color: #a9a9a9;
      opacity: 0.3;
      }
      .main-block {
      max-width: 340px;
      min-height: 330px;
      padding: 10px 0;
      margin: auto;
      border-radius: 5px;
      border: solid 1px #fff;
      box-shadow: 1px 2px 5px rgba(0,0,0,.31);
      background: #F8FFBF;
      }
      form {
      margin: 0 30px;
      }
      .account-type, .gender {
      margin: 15px 0;
      }
      input[type=radio] {
      display: none;
      }
      label#icon {
      margin: 0;
      border-radius: 5px 0 0 5px;
      }
      label.radio {
      position: relative;
      display: inline-block;
      padding-top: 4px;
      margin-right: 20px;
      text-indent: 30px;
      overflow: visible;
      cursor: pointer;
      }
      label.radio:before {
      content: "";
      position: absolute;
      top: 2px;
      left: 0;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #EED90C;
      }
      label.radio:after {
      content: "";
      position: absolute;
      width: 9px;
      height: 4px;
      top: 8px;
      left: 4px;
      border: 3px solid #fff;
      border-top: none;
      border-right: none;
      transform: rotate(-45deg);
      opacity: 0;
      }
      input[type=radio]:checked + label:after {
      opacity: 1;
      }
      input[type=text], input[type=password] {
      width: calc(100% - 57px);
      height: 36px;
      margin: 13px 0 0 -5px;
      padding-left: 10px;
      border-radius: 0 5px 5px 0;
      border: solid 1px #cbc9c9;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09);
      background: #fff;
      }
      input[type=conf-password] {
      margin-bottom: 15px;
      }
      #icon {
      display: inline-block;
      padding: 9.3px 15px;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09);
      background: #EED90C;
      color: #fff;
      text-align: center;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      .submit {
      width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px;
      border: none;
      background: #EED90C;
      font-size: 14px;
      font-weight: 600;
      color: #fff;
      }
      .submit:hover {
      background: #26a9e0;
      }

    </style>
  </head>
  {% include 'alerts.html' %}
  <body>
    <div class="main-block">
      <h1>Rejestracja</h1>
      <form method="POST" action="{{ url_for('user_management.register') }}">
        <hr>

        <hr>
        <label id="icon" for="email"><i class="fas fa-envelope"></i></label>
        {% if last_email %}
        <input type="text" class="form-control" name="email" id="email" placeholder="Email" value="{{ last_email }}"
               pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" autofocus required/>
        {% else %}
        <input type="text" class="form-control" name="email" id="email" placeholder="Email"
               pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$" autofocus required/>
        {% endif %}

        <label id="icon" for="password"><i class="fas fa-unlock-alt"></i></label>
        <input type="password" class="form-control" name="password" id="password" placeholder="Hasło" required/>

        <label id="icon" for="conf_password"><i class="fas fa-unlock-alt"></i></label>
        <input type="password" class="form-control" name="conf_password" id="conf_password" placeholder="Powtórz hasło" required/>
        <hr>

        <hr>
        <div class="btn-block">
          <p>Poprzez kliknięcie Zatwierdz, zgadzasz się na naszą <a href="https://www.w3docs.com/privacy-policy">Politykę prywatności</a>.</p>
          <button class="submit" type="submit" href="/">Zatwierdz</button>
        </div>
      </form>
    </div>

  </body>
</html>