app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectField, HiddenField
from wtforms.validators import DataRequired


class SearchForm(FlaskForm):
    searched = StringField("Searched", validators=[DataRequired()])
    submit = SubmitField("Submit")


class TripForm(FlaskForm):
    city = SelectField('city', choices=[])
    country = SelectField('city', choices=[])
    price = HiddenField('price')
    submit = SubmitField("Submit")

app/main/routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from ..trips.trip import Trip
from ..extensions import db
from .forms import SearchForm, TripForm
from sqlalchemy import func
from random import sample, seed

main = Blueprint('main', __name__, template_folder='templates')

@main.route("/", methods=['GET', 'POST'])
def index():
    # executing database
    trips = db.session.execute(db.select(Trip)).scalars()  # basic trips

    # ----------------------FILTER CITIES --------------------------------------------

    # querying database by cities, assigning CityForm and
    form = TripForm()  # dodaję instancję formularza do filtrowania
    cities = ['-']  # docelowo array wszystkich miast
    countries = ['-']  # array wszystkich unikalnych krajów
    # query of cities
    tripsv2 = db.session.query(Trip.city).distinct().all()  # array wszystkich miast jako sqlalchemy obj
    tripsv3 = db.session.query(Trip.country).distinct().all()  # array krajów jako sqlalchemy obj
    max_price = db.session.query(func.max(Trip.price)).first()[0]
    if max_price is None:
        max_price = 2000
    min_price = db.session.query(func.min(Trip.price)).first()[0]
    if min_price is None:
        min_price = 0
    tripsfiltered = Trip.query  # instancja sqlalchemy
    for item in tripsv2:
        cities.append(item.__getitem__(0))  # got the array of all cities in the database
    for item in tripsv3:
        countries.append(item.__getitem__(0))
    # passing to choice on website
    form.country.choices = countries
    form.city.choices = cities  # podanie do wyboru wszystkich możliwych miast ze słownika do formularza

    # jeżeli potwierdzono formularz to filtruj dane
    if request.method == 'POST' and form.validate_on_submit():
        filtereddatacity = form.city.data
        filtereddatacountry = form.country.data
        filtereddataprice = request.form["slider"]  # reading data from slider

        if filtereddatacountry == '-' and filtereddatacity == '-':
            tripsfiltered = tripsfiltered.filter(Trip.price <= filtereddataprice)
        elif filtereddatacountry == '-':
            tripsfiltered = tripsfiltered.filter(Trip.city == filtereddatacity,
                                                 Trip.price <= filtereddataprice)
        elif filtereddatacity == '-':
            tripsfiltered = tripsfiltered.filter(Trip.country == filtereddatacountry,
                                                 Trip.price <= filtereddataprice)
        else:
            tripsfiltered = tripsfiltered.filter(Trip.city == filtereddatacity,
                                                 Trip.country == filtereddatacountry,
                                                 Trip.price <= filtereddataprice)


        # sort by name
        tripsfiltered = tripsfiltered.order_by(Trip.name).all()
        if len(tripsfiltered) == 0:
            flash("Nie znaleziono takich wycieczek!", "error")
            return render_template('index.html', trips=trips, form=form, min_price=min_price, max_price=max_price)

        return render_template('index.html', trips=tripsfiltered, form=form, min_price=min_price, max_price=max_price)
    # jeżeli nie, to zwróć basicowe
    return render_template('index.html', trips=trips, form=form, min_price=min_price, max_price=max_price)


@main.route("/about")
def about():
    return render_template('about.html')


@main.route("/contact")
def contact():
    return render_template('contact.html')


# pass stuff to topnavbar.html

@main.context_processor  # passing stuff to a base file
def indexpass():
    form = SearchForm()
    return dict(form=form)


# creating search function

@main.route("/search", methods=['GET', 'POST'])
def search():
    searchform = SearchForm()
    trips = Trip.query
    max_price = db.session.query(func.max(Trip.price)).first()[0]
    if max_price is None:
        max_price = 2000
    min_price = db.session.query(func.min(Trip.price)).first()[0]
    if min_price is None:
        min_price = 0
    if request.method == 'POST' and searchform.validate_on_submit():
        # get data from submitted form
        searcheddata = searchform.searched.data
        # query the database

        trips = trips.filter((Trip.name.contains(searcheddata)) |
                             (Trip.city.contains(searcheddata)) |
                             (Trip.country.contains(searcheddata)) |
                             (Trip.description.contains(searcheddata))
                             )
        # sort by name
        trips = trips.order_by(Trip.name).all()

        # if found, show search html with found trips
        if len(trips) > 0:
            return render_template("search.html", form=searchform, searched=searcheddata, trips=trips)
    flash('Nie znaleziono takiej wycieczki!', 'error')
    return redirect(url_for('main.index'))  # dorobić nie znaleziono takiej wycieczki html

app/main/templates/about.html
{% extends 'base.html' %}


{% block header %}
<h1>O nas</h1>

{% endblock %}
{% block content %}
</br>
<div class="news">
<h3>Opis biura podróży</h3>
    </br>
<h6>jesteśmy cenionym biurem podróży, pracujemy w branży od tylu i tylu lat itp. </h6>
</div>
{% endblock %}

app/main/templates/alerts.html
<!DOCTYPE html>

<link href="{{ url_for('static', filename='stylesheets/alerts.css') }}" rel="stylesheet">

{% with errors = get_flashed_messages(category_filter=["error"]) %}
  {% if errors %}
    {%- for err in errors %}
      <div class="popup red_popup" id="popup">
          {{ err }}
          <button type="button" class="popup close_red_popup" onclick="closePopup()" formnovalidate><center><b>X</b></center></button>
      </div>
    {% endfor -%}
  {% endif %}
{% endwith %}

{% with messages = get_flashed_messages(category_filter=["mess"]) %}
  {% if messages %}
    {%- for msg in messages %}
      <div class="popup green_popup" id="popup">
          {{ msg }}
          <button type="button" class="popup close_green_popup" onclick="closePopup()" formnovalidate><center><b>X</b></center></button>
      </div>
    {% endfor -%}
  {% endif %}
{% endwith %}

<script>
    let popup = document.getElementById("popup");
    function openPopup(){
        popup.classList.add("open-popup");
    }
    function closePopup(){
        popup.classList.remove("open-popup");
    }
</script>

<script>
   window.onload = openPopup()
</script>

app/main/templates/base.html
<!DOCTYPE html>
<html>
<link href="{{ url_for('static', filename='stylesheets/styles.css') }}" rel="stylesheet">
{% include 'alerts.html' %}
<div class="bars">
    <div class="bar"></div>



<div class="container">
    {% include 'topnavbar.html' %}
    <div class="header">
        {% block header %} <!-- block different for many templates-->
        {% endblock %}
    </div>

        {% block sidebar %}
        <!-- sidebar to add-->
        {% endblock %}

        {% block content %}

        <!-- block content to repeat, zawartość centrum-->

        {% endblock %}
        <!-- sidebar added -->






   </div>
    <!-- zawieram htmlkę z searchbaru w naszą stronę główną-->


    <!--footer to repeat everytime -->
    <div class="bar"></div>
</div>
    <div class="footer">
        {% if current_user.is_authenticated %}
        Zalogowany jako
        {{ current_user.email }}
        {% endif %}
        <div class="bottomlinks">
            <h4>O Baloniarzach</h4>
            <ul>
                <li><a href="#">Kim jesteśmy</a></li>
                <li><a href="#">Nasi piloci</a></li>
                <li><a href="#">Nasze Hotele</a></li>
                <li><a href="#">Szkolenia turystyczne</a></li>
                <li><a href="#">Dla inwstorów</a></li>
            </ul>
        </div>
        <div class="bottomlinks">
            <h4>Dla klientów</h4>
            <ul>
                <li><a href="#">Wytyczne przed podróżą</a></li>
                <li><a href="#">Linie lotnicze</a></li>
                <li><a href="#">Opinie o nas</a></li>
                <li><a href="#">Karty i bony</a></li>
                <li><a href="#">Katalogi</a></li>
            </ul>
        </div>
        <div class="bottomlinks">
            <h4>Zasady korzystania</h4>
            <ul>
                <li><a href="#">Warunki uczestnictwa</a></li>
                <li><a href="#">Ubezpieczenie podrzóżnego</a></li>
                <li><a href="#">Politayka plików cookie</a></li>
                <li><a href="#">Regulamin serwisu</a></li>
            </ul>
        </div>
    </div>



</html>

app/main/templates/contact.html
{% extends 'base.html' %}
{% block header %}
<h1>Kontakt</h1>
{% endblock %}

{% block content %}

<div class="news">
    </br>
<h3>997</h3>

<h6> zadzwoń do nas, umówimy cię na podróż życia na dołek </h6>
</div>
{% endblock %}

app/main/templates/index.html
{% extends 'base.html' %} <!-- zawieram htmlkę, naszą stronę główną-->

<!-- zawartość main -->
<!-- header -->
{% block header %}
<h1>Biuro podróży "Kulturalni baloniarze"</h1>
{% endblock %}

{% block sidebar %}
<!-- zawartość boku, sidebara -->
<div class="sidebar">
<div class="pins" style="border-radius: 25px 25px 0 0  ;">

    <h2>Filtry</h2>

    <center>
    <form action="/">
        <input class="filter_buttons" type="submit" value="Usuń filtry"/>
    </form>
    </center>

</div>
<form action="{{url_for('main.index')}}" method="POST">
    {{ form.hidden_tag() }}
    <div class="pins" >
        <div class="container">
            <div class="column">
                <div class="row">
                    <label>Wybierz miasto: <br>{{ form.city }}</label>
                </div>
                <div class="row">
                    <label>Wybierz kraj: <br>{{ form.country }}</label>
                </div>
            </div>
        </div>
    </div>
    <div class="pins">
        {% include 'slider.html' %}
    </div>
    <center>
    <div class="pins">
        <input class="filter_buttons" type="submit" value="Filtruj">
    </div>
    </center>
</form>
    </div>
{% endblock %}

{% block content %}
<br/>
{% if request.args.get('max_loop') is not none %}
{% set max_loop = request.args.get('max_loop') | int %}
{% endif %}
<div class="news">
    {% set ns = namespace(trips_len=0) %}
    {% for trip in trips %}
    {% set ns.trips_len = ns.trips_len + 1 %}
    {% if max_loop %}
        {% if loop.index0 < max_loop %}
            <div class="article-small">
                <div class="articlecontent">
                    <img src="{{ url_for('static', filename='pictures/' + trip.image) }}">
                    <h3 class="price">{{ trip.price }} <sup style="font-size:10px"><u>PLN</u></sup></h3>
                    <h2>{{ trip.name }}</h2>
                    <h3 class="con_cit">{{ trip.country }} - {{ trip.city }}</h3>
                    {% for i in range(0, trip.stars) %}
                        {% if i % 2 == 0 %}
                            <i class="fa fa-star" id="star"></i>
                        {% elif loop.last and i % 2 != 0 %}
                            <i class="fa fa-star-half" id="star"></i>
                        {% endif %}
                    {% endfor %}
                </div>
                <a class='tripurl' href="{{url_for('trips.tripview', tripID = trip.id)}}"></a>
            </div>
        {% endif %}
    {% else %}
    <div class="article-small">
                <div class="articlecontent">
                    <img src="{{ url_for('static', filename='pictures/' + trip.image) }}">
                    <h3 class="price">{{ trip.price }} <sup style="font-size:10px"><u>PLN</u></sup></h3>
                    <h2>{{ trip.name }}</h2>
                    <h3 class="con_cit">{{ trip.country }} - {{ trip.city }}</h3>
                    {% for i in range(0, trip.stars) %}
                        {% if i % 2 == 0 %}
                            <i class="fa fa-star" id="star"></i>
                        {% elif loop.last and i % 2 != 0 %}
                            <i class="fa fa-star-half" id="star"></i>
                        {% endif %}
                    {% endfor %}
                </div>
                <a class='tripurl' href="{{url_for('trips.tripview', tripID = trip.id)}}"></a>
            </div>
    {% endif %}
    {% endfor %}
</div>
<div class="disp">
    <center>
        <p>Liczba elementów na stronie:</p>
        <a class="disp_amount" id="disp_6" href = "{{ url_for('main.index', max_loop = 6) }}"><b>6</b></a>
        <a class="disp_amount" id="disp_12" href = "{{ url_for('main.index', max_loop = 12) }}"><b>12</b></a>
        <a class="disp_amount" id="disp_all" href = "{{ url_for('main.index', max_loop = ns.trips_len) }}"><b>wszystkie</b></a>
    </center>
</div>



{% endblock %} <!-- block of news, main structure of trips-->

app/main/templates/search.html
{% extends 'base.html' %} <!-- zawieram htmlkę, naszą stronę główną-->

{% block header %}

    <h2> Oto nasze propozycje do twoich wyszukiwań..</h2>

{% endblock %}

{% block sidebar %}
{% endblock %}

{% block content %}
<br/>
<div class="news">
    {% for trip in trips %}
    <div class="article-small_notindex">
        <div class="articlecontent">
            <img src="{{ url_for('static', filename='pictures/' + trip.image) }}">
            <h3 class="price">{{ trip.price }} <sup style="font-size:10px"><u>PLN</u></sup></h3>
            <h2>{{ trip.name }}</h2>
            <h3 class="con_cit">{{ trip.country }} - {{ trip.city }}</h3>
            {% for i in range(0, trip.stars) %}
            {% if i % 2 == 0 %}
            <i class="fa fa-star" id="star"></i>
            {% elif loop.last and i % 2 != 0 %}
            <i class="fa fa-star-half" id="star"></i>
            {% endif %}
            {% endfor %}
        </div>
        <a class='tripurl' href="{{url_for('trips.tripview', tripID = trip.id)}}"></a>
    </div>
    {% endfor %}
</div>
{% endblock %}

app/main/templates/slider.html
<!DOCTYPE html>
<html>
<head>
    <meta content="width=device-width, initial-scale=1" name="viewport">
    <style>
.slidecontainer {
  width: 100%;
}

.slider {
  -webkit-appearance: none;
  width: 100%;
  height: 3px;
  background: #d3d3d3;
  outline: none;
  opacity: 0.7;
  -webkit-transition: .2s;
  transition: opacity .2s;
}

.slider:hover {
  opacity: 1;
}

.slider::-webkit-slider-thumb {
  -webkit-appearance: none;
  appearance: none;
  border-radius:5px;
  width: 10px;
  height: 10px;
  background: black;
  cursor: pointer;
}

.slider::-moz-range-thumb {
  width: 10px;
  height: 10px;
  border-radius:5px;
  background: black;
  cursor: pointer;
}




    </style>
</head>
<body>

<p>Wybierz maksymalny <br>pułap cenowy wycieczki: </p>
<div class="slidecontainer">
    <input class="slider" id="myRange" max="{{ max_price }}" min="{{ min_price }}" name="slider"
           step=".01" type="range" value="{{ (max_price+min_price)/2 }}">
    <p style="font-size:12px">Maksymalna cena: <span id="demo"></span> <small>PLN</small> </p>

</div>

<script>
var slider = document.getElementById("myRange");
var output = document.getElementById("demo");
output.innerHTML = slider.value;

slider.oninput = function() {
  output.innerHTML = this.value;
}

output.innerHTML=Math.round(output.innerHTML);


</script>

</body>
</html>

app/main/templates/topnavbar.html
<!DOCTYPE html>
<html>
<head>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="{{ url_for('static', filename='stylesheets/topnavbar.css') }}" rel="stylesheet">

</head>
<body>
<div class="topnav" id="myDIV">


    <a href="/">Strona główna</a>
    <a href="/about">O nas</a>
    <a href="/contact">Kontakt</a>
    {% if current_user.is_authenticated %}
    <a href="/favourites?user={{ current_user.id }}">Ulubione</a>
    {% endif %}
    <div class="search-container">
        <form action="{{ url_for('main.search') }}" method="POST">
            {{ form.hidden_tag() }}
            <input name="searched" placeholder="Wyszukaj..." type="text">
            <button type="submit"><i class="fa fa-search"></i></button>
        </form>
    </div>
    {% if not current_user.is_authenticated %}
    <a class='logging' href="/register">Rejestracja</a>
    <a class='logging' href="/login">Logowanie</a>
    {% endif %}
    {% if current_user.is_authenticated %}
    <a class='logging' href="/logout">Wyloguj się</a>
    {% endif %}



</div>


</body>
</html>