app/trips/routes.py
from .trip import Trip
from ..user_management.user import user_trip
from ..extensions import db
from datetime import datetime
from flask import Blueprint, render_template, request, flash, url_for, redirect
from flask_login import current_user
from random import randint
from ..main.forms import SearchForm

trips = Blueprint('trips', __name__, template_folder = 'templates')

@trips.route('/tripadd', methods=['GET', 'POST'])
def tripadd():
    if request.method == 'POST':
        name = request.form['name']
        date_start = datetime.strptime(request.form['date_start'], '%Y-%m-%d').date()
        date_end = datetime.strptime(request.form['date_end'], '%Y-%m-%d').date()
        country = request.form['country']
        city = request.form['city']
        price = request.form['price']
        description = request.form['description']
        image = request.form['image']
        stars = randint(3, 9)
        trip = Trip(name=name, country=country, date_start=date_start, date_end=date_end, city=city,
                    price=price, description=description, image=image, stars=stars)
        db.session.add(trip)
        db.session.commit()
        return render_template('tripsite.html', trip=trip)
    return render_template('tripadd.html')

@trips.route('/trip?trip=<tripID>', methods = ['GET', 'POST'])
def tripview(tripID):
    #trip = db.session.execute(db.select(Trip).where(Trip.id == tripID)).scalar()
    trip = Trip.query.filter_by(id=tripID).first()
    return render_template('tripsite.html', trip=trip)

@trips.route('/follow?trip=<tripID>', methods=['GET', 'POST'])
def follow(tripID):
    if current_user.is_authenticated:
        if current_user.is_following(tripID):
            trip = Trip.query.filter_by(id=tripID).first()
            flash("Ta wycieczka jest już dodana do ulubionych.", "error")
            return render_template('tripsite.html', trip=trip)
        trip = Trip.query.filter_by(id=tripID).first()
        current_user.followed.append(trip)
        db.session.commit()
        flash('Dodano wycieczkę do ulubionych.', 'mess')
        return redirect(url_for('trips.tripview', tripID=tripID))
    else:
        flash("Musisz być zalogowany, aby dodać wycieczkę do ulubionych!", 'error')
        return render_template('login.html')

@trips.route('/unfollow?trip=<tripID>', methods=['GET', 'POST'])
def unfollow(tripID):
    trip = Trip.query.filter_by(id=tripID).first()
    current_user.followed.remove(trip)
    db.session.commit()
    flash('Usunięto wycieczkę z ulubionych.', 'mess')
    return redirect(url_for('trips.tripview', tripID=tripID))


@trips.route('/favourites', methods=['GET'])
def favourite():
    userID = request.args.get('user')
    form = SearchForm()
    trips = db.session.execute(db.select(Trip).join(user_trip).where(user_trip.c.user_id == userID)).scalars()

    return render_template('favourites.html', trips=trips, form=form)

app/trips/templates/favourites.html
{% extends 'base.html' %}

{% block header %}
<h1>Obserwowane wycieczki</h1>
{% endblock %}

{% block content %}
<br/>
<div class="news">
    {% for trip in trips %}

    <div class="article-small_notindex">
        <div class="articlecontent">
            <img src="{{ url_for('static', filename='pictures/' + trip.image) }}">
            <h3 class="price">{{ trip.price }} <sup style="font-size:10px"><u>PLN</u></sup></h3>
            <h2>{{ trip.name }}</h2>
            <h3 class="con_cit">{{ trip.country }} - {{ trip.city }}</h3>
            {% for i in range(0, trip.stars) %}
            {% if i % 2 == 0 %}
            <i class="fa fa-star" id="star"></i>
            {% elif loop.last and i % 2 != 0 %}
            <i class="fa fa-star-half" id="star"></i>
            {% endif %}
            {% endfor %}
        </div>
        <a class='tripurl' href="{{url_for('trips.tripview', tripID = trip.id)}}"></a>
    </div>
    {% endfor %}
</div>

{% endblock %}

app/trips/templates/tripadd.html
<!DOCTYPE html>
<html>
  <head>
    <title>Simple registration form</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">
    <style>
      html, body {
      display: flex;
      justify-content: center;
      height: 100%;
      }
      body, div, h1, form, input, p, textarea {
      padding: 0;
      margin: 0;
      outline: none;
      font-family: Roboto, Arial, sans-serif;
      font-size: 16px;
      color: #666;
      }
      h1 {
      padding: 10px 0;
      font-size: 32px;
      font-weight: 300;
      text-align: center;
      }
      p {
      font-size: 12px;
      }
      hr {
      color: #a9a9a9;
      opacity: 0.3;
      }
      .main-block {
      max-width: 600px;
      min-width: 400px;
      min-height: 330px;
      padding: 10px 40px 0px 40px;
      margin: auto;
      border-radius: 5px;
      border: solid 1px #fff;
      box-shadow: 1px 2px 5px rgba(0,0,0,.31);
      background: #F8FFBF;
      }
      form {
      margin: 0 30px;
      }
      .account-type, .gender {
      margin: 15px 0;
      }
      input[type=radio] {
      display: none;
      }
      label#icon {
      margin: 0;
      border-radius: 5px 0 0 5px;
      }
      label.radio {
      position: relative;
      display: inline-block;
      padding-top: 4px;
      margin-right: 20px;
      text-indent: 30px;
      overflow: visible;
      cursor: pointer;
      }
      label.radio:before {
      content: "";
      position: absolute;
      top: 2px;
      left: 0;
      width: 20px;
      height: 20px;
      border-radius: 50%;
      background: #EED90C;
      }
      label.radio:after {
      content: "";
      position: absolute;
      width: 9px;
      height: 4px;
      top: 8px;
      left: 4px;
      border: 3px solid #fff;
      border-top: none;
      border-right: none;
      transform: rotate(-45deg);
      opacity: 0;
      }
      input[type=radio]:checked + label:after {
      opacity: 1;
      }
      input[type=text], input[type=password], input[type=number], input[type=date] input[name=text], textarea{
      width: calc(100% - 57px);
      height: 36px;
      margin: 13px 0 0 -5px;
      padding-left: 10px;
      border-radius: 0 5px 5px 0;
      border: solid 1px #cbc9c9;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09);
      background: #fff;
      }
      #description{
      padding-top: 5px;
      height: 72px;
      word-wrap: break-word;
      }
      input[type=password] {
      margin-bottom: 15px;
      }
      #icon {
      display: inline-block;
      padding: 9.3px 15px;
      box-shadow: 1px 2px 5px rgba(0,0,0,.09);
      background: #EED90C;
      color: #fff;
      text-align: center;
      }
      .btn-block {
      margin-top: 10px;
      text-align: center;
      }
      button {
      width: 100%;
      padding: 10px 0;
      margin: 10px auto;
      border-radius: 5px;
      border: none;
      background: #EED90C;
      font-size: 14px;
      font-weight: 600;
      color: #fff;
      }
      button:hover {
      background: #26a9e0;
      }
    </style>
  </head>
  <body>
    <div class="main-block">
      <h1>Rejestracja wycieczki</h1>
      <form method="POST" action="{{ url_for('trips.tripadd') }}">
        <hr>

        <hr>

        <label for="name"></label>
        <input type="text" class="form-control" id="name" name="name" placeholder="Nazwa wycieczki" autofocus required>

          <br><br/>
          <label for="date_start" padding="" >Data rozpoczęcia: </label>
          <input type="date" class="form-control" id="date_start" name="date_start" required>

          <br><br/>
          <label for="date_end">Data zakończenia: </label>
          <input type="date" class="form-control" id="date_end" name="date_end" placeholder="Data konca" required>

          <label for="country"></label>
          <input type="text" class="form-control" id="country" name="country" placeholder="Państwo" required>

          <label for="city"></label>
          <input type="text" class="form-control" id="city" name="city" placeholder="Miasto" required>

          <label for="price"></label>
          <input type="number" class="form-control" id="price" name="price" min=0 step= "0.01" placeholder="Cena" required>

          <div height = 72px;>
          <label for="description"></label>
            <textarea class="form-control" id="description" name="description" placeholder="Opis" required></textarea>
          </div>

          <label for="image">Dodaj zdjęcie:</label>
          <input type="file" class="form-control" id="image" name="image" accept="image/jpeg, image/png" required>
            <hr>
            <hr>

            <div class="btn-block">
          <button type="submit" class="btn btn-primary">Zatwierdź</button>
        </div>
      </form>
    </div>
  </body>
</html>

app/trips/templates/tripsite.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{{ url_for('static', filename='stylesheets/trip.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% include 'alerts.html' %}
<body>
<div class="bars">
    <div class="bar"></div>
    <div id="container">
        <center>
        <h2>{{ trip.country }} - {{ trip.city }}</h2>
        </center>
        <div id="topbar">
                <img src="{{ url_for('static', filename='pictures/' + trip.image) }}">
            <div id="info">
                <h3>Informacje:</h3>
                <div style="clear:both;"></div>

                <table>
                    <tr>
                        <td class="info_td">Data rozpoczęcia: </td>
                        <td class="value_td">{{ trip.date_start }}</td>
                    </tr>
                    <tr>
                        <td class="info_td">Data zakończenia: </td>
                        <td class="value_td">{{ trip.date_end }}</td>
                    </tr>
                    <tr>
                        <td class="info_td">Całkowity koszt: </td>
                        <td class="value_td">{{ trip.price }} <small>PLN</small></td>
                    </tr>
                </table>
                <div style="clear:both;"></div>
                <center>
                {% if current_user.is_authenticated and current_user.is_following(trip.id) %}
            <form action="{{ url_for('trips.unfollow', tripID = trip.id) }}" method="POST">
              <button class="fav" type="submit"><b><i class="fa fa-heart-o" style="margin:2px"></i><br/>Usuń z ulubionych</b></button>
            </form>
            {% else %}
            <form action="{{ url_for('trips.follow', tripID = trip.id) }}" method="POST">
                <button class="fav" type="submit"><b><i class="fa fa-heart" style="margin:2px"></i><br/>Dodaj do ulubionych</b></button>
            </form>
            {% endif %}
                    </center>
            </div>
        </div>
        <div style="clear:both;"></div>
        <center>
            <div id="opis">
                <h3>Opis: <a class="main_page" href = "{{ url_for('main.index')}}">Wróć na stronę główną</a></h3>
                {{ trip.description }}
            </div>
        </center>


    </div>
    <div class="bar"></div>
</div>
</body>
</html>